### ISSUE TITLE
Setup of AliceOS in Doki Doki Forces fails when it has to show the "System Modified by Manufacturer" alert

### ISSUE THREAD

**Issue by cpgyuri** [TheAngelReturns/aliceos#21]
Steps:

- I set define aliceos.oem_mode = True in **both OEMSettings.rpy and DefaultSettings.rpy**
- The boot screen show the white "AliceOS" logo with the "Powered by" text and my Ghost Sayori chibi, as I expected.
- Setup starts, but when the "System Modified by Manufacturer" alert dialog has to appear, the mod crashes.
- After the error appears, setup can't advance to the next steps, and clicking Ignore doesn't fix anything, having to close the game.

I suppose that the "System Modified" dialog has to show, because it's critical to show that "my" AliceOS copy was "modified".

Included the traceback and a screenshot.
[traceback.txt](https://github.com/TheAngelReturns/aliceos/files/2393628/traceback.txt)
![captura](https://user-images.githubusercontent.com/40330209/45701390-72534f00-bb45-11e8-8b15-fd09643e2a98.PNG)

Personal note: it would be great if I could have some support as the Sayonika mod has for having an "OEM" version with Sonic related fonts and art replacing some Alice files, since I supported this project since day one also.

**Comment by alicerunsonfedora** [comment]
This call is actually deprecated as we are implementing a screen entirely dedicated to this right here:

![screenshot0013](https://user-images.githubusercontent.com/13445064/45702214-3ae1a400-bb3f-11e8-8888-f70b609a3bad.png)
