### ISSUE TITLE
Potential trademark violation (Alice Os)

### ISSUE THREAD

**Issue by dginu85** [TheAngelReturns/aliceos#39]
Alice Os,AliceOs is copyright of one multimedia.
Please remove or rename this project.

**Comment by Bronya-Rand** [comment]
Comparing this issue with the project we have already, I can see little info on this case.

First, the users end descriptive isn't very clear or a actual lawyer issued document. Apart from mentioning the main area of the name _Alice OS_ being part of _One Multimedia_ being some evidence, not much is also given as well.

Second, this is a OSS/Free Software and we are not technically using the name _Alice OS_ with this repository to sell. That will violate both Team Salvato's (Doki Doki Literature Club's Publisher) Guidelines and Joey Drew Studios Guidelines as all mods have to be distributed as free. The Alice OS they mention is of a car operating system in Italy which has nothing to do with a _"framework"_ on a Ren'Py/Python level as it is only being made for Doki Doki Literature Club and not being sold to other third party's or anyone for that matter.

The name alone does not institute a copyright violation as we are not selling, or using anything related to One Multimedia's Alice OS and Our Alice OS is completely different and is for a visual novel that is being made for free. If you want to clarify your case here, you are able to do so as well.

**Comment by DuskEalain** [comment]
Howdy @dginu85 ! I'm Dusk and I'm here to talk a bit more about this copyright issue.

Firstly, you fail the first hurdle of the Likelihood of Confusion Test used in US Trademark disputes:

-Strength of the plaintiff's trademark.

You are using a very common name, according to Babble, "Alice" is the 70th most popular name for girls, and mixed it with the initials for Operating System.

Secondly, names and brands are trademarkable entities, not copyrightable.

Thirdly, as @GanstaKingofSA  said, One Multimedia's AliceOS project is a car OS, not a program framework, so the market share is different.

And finally, your post does not come across as professional at all.

**Comment by sr229** [comment]
@dginu85 Please raise this via our email, or thru me in at <enra@aliceos.app>.

Second of all, reviewing our legality, AliceOS is a valid GitHub project, and does not fall under any trademark violation for the reasons:

-  We do NOT earn any profit from using this, and this is a Open Source project, meaning, any proprietary tool should not be confused with this project.

- Alice IS NOT copyrightable, therefore this is rather invalid to be raised as such as a copyright violation as AliceOS is not even copyrighted trademark. We reserve every right to have a project name as such.

- And you do NOT represent One Multimedia, if your REALLY represent One Multimedia, you should've contacted us in our proper legal channels, or through GitHub's DMCA system.

Closing as this more of a scare tactic. FUD doesn't work here. This isn't 2004 anymore.

**Comment by sr229** [comment]
And forgot to tell you, I require a LEGAL manifest that this is affecting the company, but no you don't have, because you DON'T represent One Multimedia.
